const V=(()=>{const q=new URLSearchParams(location.search).get('v'),b=document.body.dataset.v;let v=b&&b!=='auto'?b:(q||(()=>{try{return localStorage.getItem('ln_v')}catch(e){}})()||'corp');if(v!=='fun')v='corp';try{localStorage.setItem('ln_v',v)}catch(e){}document.body.classList.add('v-'+v);return v})();
const HOME=V==='fun'?'fun.html':'index.html';
const pimg=(k,i)=>{const p=P[k];const src=i!=null&&p.imgs?p.imgs[i]:p.img;return p.photo?'<img class="ph" src="'+src+'" alt="'+p.name+'" loading="lazy">':'<img class="cut" src="'+src+'" alt="'+p.name+'" loading="lazy">'};
(function(){
 const here=location.pathname.split('/').pop()||'index.html';
 const nav=[[HOME,'Accueil',''],['produits.html','Nos produits','<span class="pst n">9</span>'],[HOME+'#marques','Marques',''],['distributeurs.html','Distributeurs','<span class="pst b">pro</span>'],[HOME+'#contact','Contact','']];
 const act=h=>h.split('#')[0]===here&&!h.includes('#')?' class="act"':'';
 document.getElementById('hdr').innerHTML='<header class="top" id="top-h"><a class="logo" href="'+HOME+'"><img src="img/logo-liner.png" alt="Liner"></a><nav aria-label="Menu principal">'+nav.map(n=>'<a href="'+n[0]+'"'+act(n[0])+'>'+n[1]+n[2]+'</a>').join('')+'</nav><div class="hr"><a class="cta" href="distributeurs.html">Devenir distributeur</a><button class="burger" type="button" aria-label="Ouvrir le menu">☰</button></div></header><div class="menu" id="menu"><button class="mx" type="button" aria-label="Fermer">✕</button>'+nav.map(n=>'<a href="'+n[0]+'">'+n[1]+n[2]+'</a>').join('')+'</div>';
 const other=V==='fun'?'corp':'fun',u=new URL(location.href);u.searchParams.set('v',other);u.hash='';
 let tgt=u.pathname.split('/').pop()||'index.html';if(tgt==='index.html'||tgt==='fun.html')tgt=other==='fun'?'fun.html':'index.html';
 const sw=document.createElement('a');sw.className='vswitch';sw.href=tgt+u.search;
 sw.innerHTML=V==='fun'?'<span class="vs-i">🏢</span><span><small>Passer en</small>Version corporate</span>':'<span class="vs-i">🍫</span><span><small>Découvrir la</small>Version gourmande</span>';document.body.appendChild(sw);
 const f=document.getElementById('ftr');if(f)f.innerHTML='<footer class="ft"><div class="wrap fg"><div><img src="img/logo-liner.png" alt="Liner" class="flogo"><p>'+CO.legal+'. Chocolaterie et biscuiterie depuis '+CO.since+'. Le goût du bonheur à chaque bouchée.</p></div><div><h4>Gammes</h4>'+Object.keys(CAT).map(c=>'<a href="produits.html?cat='+c+'">'+CAT[c][0]+'</a>').join('')+'</div><div><h4>Marques</h4>'+ORDER.slice(0,6).map(k=>'<a href="produit.html?p='+k+'">'+P[k].name+'</a>').join('')+'</div><div><h4>Contact</h4><a href="tel:'+CO.telh+'">'+CO.tel+'</a><a href="mailto:'+CO.mail+'">'+CO.mail+'</a><p class="fa">Usine : '+CO.usine+'</p><p class="fa">Siège : '+CO.siege+'</p></div></div><div class="wrap fb"><span>© '+CO.legal+'</span><span>Maquette réalisée par Webminds</span></div></footer>';
 const b=document.createElement('div');b.id='wm-demo';b.textContent='Maquette de démonstration réalisée par Webminds · Proposition non officielle, aucun formulaire n\'est enregistré';document.body.appendChild(b);
 const m=document.getElementById('menu');
 document.addEventListener('click',e=>{if(e.target.closest('.burger'))m.classList.add('open');if(e.target.closest('.mx')||e.target.closest('.menu a'))m.classList.remove('open')});
 const th=document.getElementById('top-h');const s=()=>th.classList.toggle('solid',scrollY>30);addEventListener('scroll',s,{passive:true});s();
 const io=new IntersectionObserver(es=>es.forEach(x=>{if(x.isIntersecting){x.target.classList.add('in');io.unobserve(x.target)}}),{threshold:.08});
 window.reveal=()=>document.querySelectorAll('.rv:not([data-o])').forEach(e=>{e.dataset.o=1;io.observe(e)});reveal();
})();
function okForm(f,msg){const b=f.querySelector('button[type=submit]'),t=b.textContent;b.textContent=msg;b.disabled=true;b.classList.add('done');setTimeout(()=>{f.reset();b.textContent=t;b.disabled=false;b.classList.remove('done')},3200)}
const WILAYAS='Adrar,Chlef,Laghouat,Oum El Bouaghi,Batna,Béjaïa,Biskra,Béchar,Blida,Bouira,Tamanrasset,Tébessa,Tlemcen,Tiaret,Tizi Ouzou,Alger,Djelfa,Jijel,Sétif,Saïda,Skikda,Sidi Bel Abbès,Annaba,Guelma,Constantine,Médéa,Mostaganem,M\'Sila,Mascara,Ouargla,Oran,El Bayadh,Illizi,Bordj Bou Arréridj,Boumerdès,El Tarf,Tindouf,Tissemsilt,El Oued,Khenchela,Souk Ahras,Tipaza,Mila,Aïn Defla,Naâma,Aïn Témouchent,Ghardaïa,Relizane,Timimoun,Bordj Badji Mokhtar,Ouled Djellal,Béni Abbès,In Salah,In Guezzam,Touggourt,Djanet,El M\'Ghair,El Meniaa'.split(',');
function contactInit(){const w=document.getElementById('cw');if(w)w.innerHTML=WILAYAS.map(x=>'<option>'+x+'</option>').join('');const f=document.getElementById('cform');if(f)f.onsubmit=e=>{e.preventDefault();okForm(e.target,'Message envoyé !')}}
